<div class="content__inner" id="bouwkundig-ontwerper--algemeen--specialist">
   <h2>   Wat is en wat doet een bouwkundig ontwerper ( algemeen ) specialist? </h2>   
   <br>
<h4>   Bouwkundig tekenaar / ontwerper</h4>   
<p>     Een bouwkundig tekenaar / ontwerper is een vakman of vakvrouw die technische tekeningen maakt voor bouwkundige toepassingen, constructies en gebouwen. Het tekenen van technische bouwtekeningen is niet heel makkelijk, omdat bouwkundige tekeningen aan veel eisen moeten voldoen voordat ze door opdrachtgevers en gemeentes geaccepteerd worden. Een bouwkundig tekenaar zal in de meeste gevallen diverse concepttekeningen maken, voordat er een uiteindelijke goedkeuring kan plaatsvinden. Over het algemeen is het zo dat technische bouwtekeningen zeer uitgebreid zijn, omdat er veel informatie opgenomen moeten worden binnen de technische tekeningen. Daarnaast is het zo dat technische tekeningen voorzien kunnen zijn van diverse detailtekeningen. Binnen deze detailtekeningen worden bepaalde constructies vergroot uitgelegd, zodat er makkelijker te zien is hoe de constructie precies opgebouwd moet worden. De werkzaamheden van een bouwkundig tekenaar zijn aan te merken als zeer gespecialiseerde werkzaamheden, die ook om de nodige vakkennis en bouwkennis vragen. Tijdens het bouwkundig tekenproces zijn meestal diverse partijen betrokken zoals de opdrachtgevers, architecten, aannemers en gemeentes. Al deze verschillende partijen bekijken en beoordelen die bouwtekeningen op de voor hun belangrijke punten. Als bouwkundig tekenaar zal je vandaag de dag veelal met het tekenprogramma AutoCAD werken. Het tekenprogramma AutoCAD maakt het mogelijk om zeer complexe technische bouwkundige tekeningen op de computer uit te werken. Daarnaast het is niet ondenkbaar dat een bouwkundig tekenaar met de hand bepaalde tekeningen maakt. </p>    
<p>     Om als bouwkundig tekenaar te kunnen werken moet je over veel ervaring en kennis van de bouwwereld beschikken. Vooral het kunnen begrijpen van complexe details is als bouwkundig tekenaar erg belangrijk. Het technisch tekenen van gebouwen met alle details en constructies is alleen mogelijk als een bouwkundig tekenaar op de hoogte is van alle details. Het is een architect die een gebouw in ruwe vorm zal ontwerpen en het is een bouwkundig tekenaar die het gebouw technisch mogelijk maakt door het uitwerken van alle technische details. Over het algemeen zal een bouwkundig tekenaar verschillende soorten bouwtekeningen maken, zoals ontwerptekeningen, bestektekeningen, werktekeningen en bouwaanvraagtekeningen. Daarnaast is het denkbaar dat een bouwkundig tekenaar verantwoordelijk is voor het maken van bestekboeken. Naast het tekenen zelf zal een bouwkundig tekenaar veel moeten overleggen met andere betrokken partijen die allemaal verantwoordelijk zijn voor specifieke werkzaamheden, zoals een architect, constructeur, gemeente en de opdrachtgever. </p>    

<h6>     De taken van een bouwkundig ontwerper ( algemeen ) ontwerper zijn dan ook : </h6>    
<ul>  
<li>    De bouwkundig ontwerper ( algemeen )  regelt een planning en verzorgd deze ook. </li>    
<li>    De bouwkundig ontwerper ( algemeen )  regelt de tekeningen van A tot Z. ( tenzij anders overeen gekomen in overeenkomst ). </li>    
<li>    De bouwkundig ontwerper kan u adviseren. </li>    
</ul>  
<p>   <b>  Bent u van plan om een bouwkundig ontwerper ( algemeen ) specialist in te schakelen? Dan zit u bij verzekerd te werk op de goede plek! Meld u snel aan om uw klus te plaatsen en zo uw geweldig project te kunnen realiseren! </b></p>    

    <button class="btn btn-success js-aanmelden">Meld je nu aan</button>
</div>